export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';

export const ADD_SNACK = 'ADD_SNACK';
export const REMOVE_SNACK = 'REMOVE_SNACK';
export const UPDATE_SNACK = 'UPDATE_SNACK';

export const ADD_BREAKFAST = 'ADD_BREAKFAST';
export const REMOVE_BREAKFAST = 'REMOVE_BREAKFAST';
export const UPDATE_BREAKFAST = 'UPDATE_BREAKFAST';

export const ADD_LUNCH = 'ADD_LUNCH';
export const REMOVE_LUNCH = 'REMOVE_LUNCH';
export const UPDATE_LUNCH = 'UPDATE_LUNCH';

export const ADD_DINER = 'ADD_DINER';
export const REMOVE_DINER = 'REMOVE_DINER';
export const UPDATE_DINER = 'UPDATE_DINER';


